package Exception;

/*public class UserException {

	//public static void main(String[] args) throws UserException {
		//int x=10;
	//	int y=0;
		try {
			int z=x/y;
			 
			if(z==0) {
				throw new Exception("using user define exception");
			}
			System.out.println(z);
		}
		catch(UserException e) {
			System.err.println("error");
			
		}

	}

}
*/